name: daily_planner
description: 每日计划 - 计划、记账、喝水提醒
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.9
  dio: ^5.4.0
  flutter_local_notifications: ^16.3.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  glados: ^1.1.1

flutter:
  uses-material-design: true
